### ISSUE TITLE
Incorrect baud rate for Beagle Connect UART

### ISSUE THREAD

**Issue by statropy** [statropy/msp430F55xx_usb_uart_bridge#6]
Still need to determine actual baud rate. UART configured to use 20MHz SMCLK to generate 115200bps. The FLL and SMCLK are generated from the internal 32kHz REFO clock, so the XT2 crystal speed should not be a factor.

**Comment by Pillar1989** [comment]
https://github.com/statropy/msp430F55xx_usb_uart_bridge/pull/8

**Comment by statropy** [comment]
The 24MHz clock/baud rate generator settings also work with the Launchpad that uses a 4MHz crystal.

**Comment by statropy** [comment]
Works as expected on Beagle Connect Rev C. SMCLK clock is independent of the XT2 crystal.
